/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bl.DiceTableModel;
import bl.DiceTableRenderer;
import bl.KniffelBL;
import bl.KniffelTableRenderer;
import bl.KniffelTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author oskar
 */
public class GUI extends javax.swing.JFrame {

    private KniffelBL bl = new KniffelBL();
    private KniffelTableModel ktm = new KniffelTableModel();
    private DiceTableModel dtm = new DiceTableModel();
    private DiceTableRenderer dtr = new DiceTableRenderer();
    private KniffelTableRenderer ktr = new KniffelTableRenderer();
    private int ObereSumme, UntereSumme, GesamtPunkte;
    private static int ObererBonus = 35;

    public GUI() {
        initComponents();
        tableKniffel.setModel(ktm);
        tableKniffel.setDefaultRenderer(Object.class, ktr);
        tableDices.setModel(dtm);
        tableDices.setDefaultRenderer(Object.class, dtr);
        tableDices.setCellSelectionEnabled(false);

        tableKniffel.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btWurfeln = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKniffel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfObereSumme = new javax.swing.JTextField();
        tfObererBonus = new javax.swing.JTextField();
        tfUntereSumme = new javax.swing.JTextField();
        tfGesamtPunkte = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btWurfeln.setBackground(new java.awt.Color(0, 0, 0));
        btWurfeln.setForeground(new java.awt.Color(255, 255, 255));
        btWurfeln.setText("würfeln");
        btWurfeln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWurfelnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gewinnkarte"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        tableKniffel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKniffel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKniffelMouseClicked(evt);
            }
        });
        tableKniffel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKniffelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tableKniffelKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tableKniffel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Punkte"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Obere Summe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Oberer Bonus:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Untere Summe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel4.setText("gesamt-Punkte:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jLabel4, gridBagConstraints);

        tfObereSumme.setEditable(false);
        tfObereSumme.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(tfObereSumme, gridBagConstraints);

        tfObererBonus.setEditable(false);
        tfObererBonus.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(tfObererBonus, gridBagConstraints);

        tfUntereSumme.setEditable(false);
        tfUntereSumme.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(tfUntereSumme, gridBagConstraints);

        tfGesamtPunkte.setEditable(false);
        tfGesamtPunkte.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(tfGesamtPunkte, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel3, gridBagConstraints);

        tableDices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDices.setMaximumSize(new java.awt.Dimension(60, 60));
        tableDices.setMinimumSize(new java.awt.Dimension(60, 60));
        tableDices.setRowHeight(50);
        tableDices.setTableHeader(null);
        jScrollPane2.setViewportView(tableDices);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btWurfeln, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btWurfeln, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btWurfelnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWurfelnActionPerformed
        tableDices.setCellSelectionEnabled(true);
        dtm.setStable(dtr.getStable());
        dtm.dice();
        int dices = dtm.getDicetries();
        if (dices != 0) {
            tableKniffel.setEnabled(true);
        }
        btWurfeln.setText("würfeln (" + (3 - dtm.getDicetries()) + ")");
    }//GEN-LAST:event_btWurfelnActionPerformed

    private void tableKniffelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKniffelKeyPressed

    }//GEN-LAST:event_tableKniffelKeyPressed

    private void tableKniffelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKniffelKeyTyped

    }//GEN-LAST:event_tableKniffelKeyTyped

    private void tableKniffelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKniffelMouseClicked

        if (tableKniffel.isEnabled()) {
            if (dtm.getDicetries() <= 3) {
                int row = tableKniffel.getSelectedRow();

                if (ktm.getRow(row).isSelected()) {

                    try {
                        int punkte = bl.chooseSpiel(row, dtm.getDices());
                        if (tableKniffel.getSelectedRow() < 6) {
                            ObereSumme += punkte;

                            tfObereSumme.setText("" + ObereSumme);
                        } else {
                            UntereSumme += punkte;
                            tfUntereSumme.setText("" + UntereSumme);
                        }
                        if (ObereSumme >= 63) {
                            GesamtPunkte = ObereSumme + UntereSumme + ObererBonus;
                            tfObererBonus.setText("" + ObererBonus);
                        } else {
                            GesamtPunkte = ObereSumme + UntereSumme;
                        }
                        tfGesamtPunkte.setText("" + GesamtPunkte);
                        ktm.setPoints(row, punkte);
                        dtm.setDicetries();
                        btWurfeln.setText("würfeln (3)");
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    }
                }
            }
        }
        tableKniffel.setEnabled(false);
        tableDices.setCellSelectionEnabled(false);
    }//GEN-LAST:event_tableKniffelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btWurfeln;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDices;
    private javax.swing.JTable tableKniffel;
    private javax.swing.JTextField tfGesamtPunkte;
    private javax.swing.JTextField tfObereSumme;
    private javax.swing.JTextField tfObererBonus;
    private javax.swing.JTextField tfUntereSumme;
    // End of variables declaration//GEN-END:variables
}
